import json
import os
import random
import re
import subprocess
import urllib.error
import urllib.request


DEFAULT_OLLAMA_URL = "http://192.168.1.169:11434"
DEFAULT_OLLAMA_MODEL = "gemma4:e4b"

PROMPTS = {
    "p1": {
        "hotkey": "t+1",
        "label": "Enemy tilt",
        "audience": "enemy",
        "instruction": (
            "Find the enemy who is most likely tilted, currently weak, or losing direct duels against me. "
            "Use real match facts only: score, my K-D, their K-D, live duel kills/deaths, and recent killed_by_agent. "
            "Write a safe personalized jab that makes that enemy doubt themselves without clear insults."
        )
    },
    "p2": {
        "hotkey": "t+2",
        "label": "Team reset",
        "audience": "ally",
        "instruction": (
            "Motivate my own team when the match is close or going badly. "
            "Use score and my contribution if useful. "
            "Make it weird, pseudo-philosophical, and short, like a strange coach quote from another dimension."
        )
    },
    "p3": {
        "hotkey": "t+3",
        "label": "Lost GG",
        "audience": "enemy",
        "instruction": (
            "Write a GG for the end of a lost match where my team lost but my individual stats still look strong. "
            "Use my kills/deaths or duel data if it supports the line. "
            "Sound calm, smug, and safe, not salty."
        )
    },
    "p4": {
        "hotkey": "t+4",
        "label": "Objective clapback",
        "audience": "ally",
        "instruction": (
            "Reply to a teammate who complains that I do not have enough kills. "
            "Defend me with objective impact: KAST, assists, trades, space, utility, spike or survival value. "
            "Never attack my team; make it a short calm clapback."
        )
    },
    "p5": {
        "hotkey": "t+5",
        "label": "WTF random",
        "audience": "lobby",
        "instruction": (
            "Write a completely unexpected Valorant lobby message. "
            "It can be absurd, philosophical, fake-profound, or surreal, but still connected loosely to the current match context. "
            "The goal is to make everyone pause for one second and wonder what that was."
        )
    },
    "disclaimer": {
        "hotkey": "t+g",
        "label": "Gamma disclaimer",
        "audience": "lobby",
        "instruction": "Copy the fixed disclaimer."
    }
}

FIXED_DISCLAIMER = "All my messages was generated by Gamma 4 Google LLM"


def load_env(path=".env"):
    if not os.path.exists(path):
        return

    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue

            key, value = line.split("=", 1)
            os.environ.setdefault(key.strip(), value.strip().strip('"').strip("'"))


def ollama_settings():
    load_env()
    return {
        "url": os.environ.get("OLLAMA_URL", DEFAULT_OLLAMA_URL).rstrip("/"),
        "model": os.environ.get("OLLAMA_MODEL", DEFAULT_OLLAMA_MODEL),
        "timeout": float(os.environ.get("OLLAMA_TIMEOUT", "8")),
        "temperature": float(os.environ.get("OLLAMA_TEMPERATURE", "0.9")),
        "keep_alive": os.environ.get("OLLAMA_KEEP_ALIVE", "45m"),
        "player_name": os.environ.get("PLAYER_NAME", "Yotakipa")
    }


def public_prompts():
    return [
        {
            "id": prompt_id,
            "hotkey": prompt["hotkey"].upper(),
            "label": prompt["label"],
            "audience": prompt["audience"]
        }
        for prompt_id, prompt in PROMPTS.items()
    ]


def compact_player(row, player_name):
    name = row.get("name") or ""
    return {
        "team": row.get("team"),
        "slot": row.get("slot"),
        "name": row.get("name"),
        "is_me": name.lower() == player_name.lower(),
        "agent": row.get("agent"),
        "rank": row.get("rank"),
        "level": row.get("level"),
        "kd": row.get("kd"),
        "assists": row.get("assists"),
        "kast": row.get("kast"),
        "kpr": row.get("kpr"),
        "fkfd": row.get("fkfd")
    }


def compact_state(state):
    latest = state.get("latest") or {}
    settings = ollama_settings()
    scoreboard = [
        compact_player(row, settings["player_name"])
        for row in latest.get("scoreboard", [])
    ]

    return {
        "game_id": state.get("current_game_id"),
        "my_player_name": settings["player_name"],
        "score": latest.get("score") or state.get("score"),
        "me": next((row for row in scoreboard if row.get("is_me")), None),
        "scoreboard": scoreboard,
        "live_duels": latest.get("live_duels", []),
        "recent_deaths": state.get("death_log", [])[-3:],
        "pipeline": {
            "mode": "full" if latest.get("full_scan") else "fast",
            "scan_ms": latest.get("scan_ms"),
            "cache_hits": latest.get("cache_hits"),
            "cache_misses": latest.get("cache_misses")
        }
    }


def choose_mention_target(context, audience):
    rows = context.get("scoreboard", [])

    if audience == "ally":
        candidates = [row for row in rows if row.get("team") == "allies" and row.get("name")]
    else:
        candidates = [row for row in rows if row.get("team") == "enemies" and row.get("name")]

    if not candidates or random.random() >= 0.33:
        return ""

    return random.choice(candidates).get("name", "")


def build_prompt(prompt_id, state):
    prompt = PROMPTS[prompt_id]
    context = compact_state(state)
    mention = choose_mention_target(context, prompt["audience"])
    settings = ollama_settings()

    prompt_text = (
        "You write exactly one Valorant chat message in French or franglais.\n"
        "Maximum one short sentence, 120 characters max. No explanation, no quotes, no markdown.\n"
        "Safety: no clear insults, slurs, threats, harassment, sexual content, self-harm, or ban-risk words.\n"
        "Never flame my own team. Enemy jabs may be annoying, smug, confusing or psychological, but stay safe.\n"
        "Ignore headshot percentage completely; HS% is not a useful signal for this assistant.\n"
        f"My in-game name is {settings['player_name']}. Treat that player as me even if OCR is weird.\n"
        "Use Valorant slang naturally if useful: btw, ez, smurf, diff, mental, clutch, trade, KAST, lurk, swing.\n"
        "You may use random philosophical or famous-sounding phrasing if it makes the lobby say WTF.\n"
        "Prefer real match facts over generic lines: score, my K-D, assists, KAST, live duels, recent deaths and who killed me.\n"
        f"Task: {prompt['instruction']}\n"
        f"Optional mention target, use only if it helps and keep the message safe: {mention}\n"
        f"Match context JSON: {json.dumps(context, ensure_ascii=False)}"
    )

    return {
        "model": settings["model"],
        "stream": False,
        "keep_alive": settings["keep_alive"],
        "options": {
            "temperature": settings["temperature"],
            "num_predict": 48
        },
        "prompt": prompt_text
    }


def sanitize_chat_line(text):
    line = re.sub(r"\s+", " ", (text or "").strip())
    line = line.split("\n", 1)[0].strip('"').strip("'").strip()

    banned_fragments = [
        "fuck", "shit", "bitch", "retard", "suicide", "kill yourself",
        "fdp", "pute", "ntm", "tg", "connard", "salope"
    ]
    lowered = line.lower()

    for fragment in banned_fragments:
        if fragment in lowered:
            return "btw your mental economy is on eco"

    if len(line) > 120:
        line = line[:117].rstrip() + "..."

    return line or "btw the spike has more philosophy than us"


def copy_to_clipboard(text):
    subprocess.run(
        ["powershell", "-NoProfile", "-Command", "Set-Clipboard -Value $input"],
        input=text,
        text=True,
        check=True
    )


def generate_message(prompt_id, state):
    if prompt_id == "disclaimer":
        copy_to_clipboard(FIXED_DISCLAIMER)
        return FIXED_DISCLAIMER, "fixed disclaimer"

    if prompt_id not in PROMPTS:
        raise ValueError(f"Unknown prompt id: {prompt_id}")

    settings = ollama_settings()
    payload = build_prompt(prompt_id, state)
    sent_prompt = payload["prompt"]
    data = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(
        f"{settings['url']}/api/generate",
        data=data,
        headers={"Content-Type": "application/json"},
        method="POST"
    )

    try:
        with urllib.request.urlopen(req, timeout=settings["timeout"]) as response:
            body = json.loads(response.read().decode("utf-8"))
    except urllib.error.URLError as exc:
        raise RuntimeError(f"Ollama unavailable: {exc}") from exc

    message = sanitize_chat_line(body.get("response", ""))
    copy_to_clipboard(message)
    return message, sent_prompt


def warm_model():
    settings = ollama_settings()
    payload = {
        "model": settings["model"],
        "prompt": "ready",
        "stream": False,
        "keep_alive": settings["keep_alive"],
        "options": {
            "num_predict": 1,
            "temperature": 0
        }
    }
    req = urllib.request.Request(
        f"{settings['url']}/api/generate",
        data=json.dumps(payload).encode("utf-8"),
        headers={"Content-Type": "application/json"},
        method="POST"
    )

    with urllib.request.urlopen(req, timeout=max(settings["timeout"], 60)) as response:
        response.read()
