import json
import os
import random
import re
import subprocess
import urllib.error
import urllib.request


DEFAULT_OLLAMA_URL = "http://192.168.1.169:11434"
DEFAULT_OLLAMA_MODEL = "llama3.2:3b"

PROMPTS = {
    "p1": {
        "hotkey": "t+u",
        "label": "Enemy tilt",
        "audience": "enemy",
        "instruction": (
            "Find the enemy who is most likely tilted, currently weak, or losing direct duels against me. "
            "Use real match facts only: score, my K-D, their K-D, live duel kills/deaths, and recent killed_by_agent. "
            "Write a safe personalized jab that makes that enemy doubt themselves without clear insults."
        )
    },
    "p2": {
        "hotkey": "t+i",
        "label": "Team reset",
        "audience": "ally",
        "instruction": (
            "Motivate my own team when the match is close or going badly. "
            "Use score and my contribution if useful. "
            "Make it weird, pseudo-philosophical, and short, like a strange coach quote from another dimension."
        )
    },
    "p3": {
        "hotkey": "t+o",
        "label": "Lost GG",
        "audience": "enemy",
        "instruction": (
            "Write a GG for the end of a lost match where my team lost but my individual stats still look strong. "
            "Use my kills/deaths or duel data if it supports the line. "
            "Sound calm, smug, and safe, not salty."
        )
    },
    "p4": {
        "hotkey": "t+p",
        "label": "Objective clapback",
        "audience": "ally",
        "instruction": (
            "Reply to a teammate who complains that I do not have enough kills. "
            "Defend me with objective impact: KAST, assists, trades, space, utility, spike or survival value. "
            "Never attack my team; make it a short calm clapback."
        )
    },
    "p5": {
        "hotkey": "t+j",
        "label": "WTF random",
        "audience": "lobby",
        "instruction": (
            "Write a completely unexpected Valorant lobby message. "
            "It can be absurd, philosophical, fake-profound, or surreal, but still connected loosely to the current match context. "
            "The goal is to make everyone pause for one second and wonder what that was."
        )
    },
    "p6": {
        "hotkey": "t+l",
        "label": "Last killer taunt",
        "audience": "enemy",
        "target": "last_killer",
        "instruction": (
            "Taunt the enemy who killed me most recently. "
            "Use only the latest death and live duel facts. "
            "Do not pretend I killed them if the data says they killed me. "
            "Do not mention any number count ratio or score. "
            "Make it sound like I am coming back for them next round."
        )
    },
    "disclaimer": {
        "hotkey": "t+k",
        "label": "Ollama disclaimer",
        "audience": "lobby",
        "instruction": "Copy the fixed disclaimer."
    }
}

FIXED_DISCLAIMER = "All my messages were generated by a local Llama 3.2 LLM"


def load_env(path=".env"):
    if not os.path.exists(path):
        return

    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue

            key, value = line.split("=", 1)
            os.environ.setdefault(key.strip(), value.strip().strip('"').strip("'"))


def ollama_settings():
    load_env()
    return {
        "url": os.environ.get("OLLAMA_URL", DEFAULT_OLLAMA_URL).rstrip("/"),
        "model": os.environ.get("OLLAMA_MODEL", DEFAULT_OLLAMA_MODEL),
        "timeout": float(os.environ.get("OLLAMA_TIMEOUT", "8")),
        "temperature": float(os.environ.get("OLLAMA_TEMPERATURE", "0.9")),
        "keep_alive": os.environ.get("OLLAMA_KEEP_ALIVE", "45m"),
        "player_name": os.environ.get("PLAYER_NAME", "Yotakipa")
    }


def public_prompts():
    return [
        {
            "id": prompt_id,
            "hotkey": prompt["hotkey"].upper(),
            "label": prompt["label"],
            "audience": prompt["audience"]
        }
        for prompt_id, prompt in PROMPTS.items()
        if prompt_id != "disclaimer"
    ]


def compact_player(row, player_name):
    name = row.get("name") or ""
    return {
        "team": row.get("team"),
        "slot": row.get("slot"),
        "name": row.get("name"),
        "is_me": name.lower() == player_name.lower(),
        "agent": row.get("agent"),
        "rank": row.get("rank"),
        "level": row.get("level"),
        "kd": row.get("kd"),
        "assists": row.get("assists"),
        "kast": row.get("kast"),
        "kpr": row.get("kpr"),
        "fkfd": row.get("fkfd")
    }


def normalized_stat(value):
    return re.sub(r"\s+", "", str(value or "")).lower()


def suspect_scoreboard_stats(rows):
    kd_values = [normalized_stat(row.get("kd")) for row in rows if row.get("kd")]
    kast_values = [normalized_stat(row.get("kast")) for row in rows if row.get("kast")]

    if len(kd_values) >= 6:
        most_common_kd = max(kd_values.count(value) for value in set(kd_values))

        if most_common_kd / len(kd_values) >= 0.7:
            return True

    if len(kast_values) >= 6:
        hundred_count = sum(1 for value in kast_values if value in ["100%", "100"])

        if hundred_count / len(kast_values) >= 0.7:
            return True

    return False


def agent_to_enemy_name(scoreboard, agent):
    agent = (agent or "").lower()

    for row in scoreboard:
        if row.get("team") == "enemies" and (row.get("agent") or "").lower() == agent:
            return row.get("name")

    return ""


def compact_state(state):
    latest = state.get("latest") or {}
    settings = ollama_settings()
    scoreboard = [
        compact_player(row, settings["player_name"])
        for row in latest.get("scoreboard", [])
    ]
    stats_reliable = not suspect_scoreboard_stats(scoreboard)
    duels = []

    for row in latest.get("live_duels", []):
        agent = row.get("agent")
        duels.append({
            "slot": row.get("slot"),
            "agent": agent,
            "enemy_name": agent_to_enemy_name(scoreboard, agent),
            "i_killed_them": row.get("kills"),
            "they_killed_me": row.get("deaths")
        })

    last_deaths = []

    for row in state.get("death_log", [])[-2:]:
        agent = row.get("killed_by_agent")
        last_deaths.append({
            **row,
            "enemy_name": agent_to_enemy_name(scoreboard, agent)
        })

    return {
        "my_name": settings["player_name"],
        "score": latest.get("score") or state.get("score"),
        "scoreboard_stats_reliable": stats_reliable,
        "me": next((row for row in scoreboard if row.get("is_me")), None),
        "players": scoreboard,
        "duels": duels,
        "last_deaths": last_deaths
    }


def choose_mention_target(context, audience):
    if audience == "last_killer":
        deaths = context.get("last_deaths", [])

        if deaths:
            return mention_name(deaths[-1].get("enemy_name"))

        return ""

    rows = context.get("players", [])

    if audience == "ally":
        candidates = [row for row in rows if row.get("team") == "allies" and row.get("name") and not row.get("is_me")]
    else:
        candidates = [row for row in rows if row.get("team") == "enemies" and row.get("name")]

    mentionable = [row for row in candidates if mention_name(row.get("name"))]

    if not mentionable or random.random() >= 0.33:
        return ""

    return mention_name(random.choice(mentionable).get("name"))


def mention_name(name):
    name = (name or "").strip()

    if not name or re.search(r"\s", name):
        return ""

    if not re.fullmatch(r"[\w]+", name, flags=re.UNICODE):
        return ""

    return f"@{name} "


def context_lines(context, prompt_id=None):
    if prompt_id == "p6":
        deaths = context.get("last_deaths", [])

        if not deaths:
            return "Last killer: unknown"

        latest_death = deaths[-1]
        target = latest_death.get("enemy_name") or latest_death.get("killed_by_agent") or "unknown"

        return (
            f"Last killer target only: {target}\n"
            f"Last killer agent: {latest_death.get('killed_by_agent')}\n"
            "This enemy killed me most recently\n"
            "Do not mention any other enemy agent player or count"
        )

    lines = [
        f"Local player name used only to identify my own stats: {context.get('my_name')}",
        "Never target mention or mock the local player",
        f"Score: {context.get('score')}"
    ]

    me = context.get("me")
    if me and context.get("scoreboard_stats_reliable"):
        lines.append(
            "My stats: "
            f"agent={me.get('agent')} kd={me.get('kd')} "
            f"assists={me.get('assists')} kast={me.get('kast')}"
        )
    elif me:
        lines.append(f"My known identity: agent={me.get('agent')} scoreboard_stats=unreliable_do_not_use")

    enemies = [row for row in context.get("players", []) if row.get("team") == "enemies"][:5]
    if enemies:
        lines.append(
            "Enemies: "
            + "; ".join(
                (
                    f"{row.get('name')} {row.get('agent')} kd={row.get('kd')} kast={row.get('kast')}"
                    if context.get("scoreboard_stats_reliable")
                    else f"{row.get('name')} {row.get('agent')}"
                )
                for row in enemies
            )
        )

    duels = context.get("duels", [])[:5]
    if duels:
        lines.append(
            "Live duels: "
            + "; ".join(
                (
                    f"vs {row.get('enemy_name') or row.get('agent')} "
                    f"agent={row.get('agent')} "
                    f"I killed them {row.get('i_killed_them')} times "
                    f"they killed me {row.get('they_killed_me')} times"
                )
                for row in duels
            )
        )

    deaths = context.get("last_deaths", [])
    if deaths:
        lines.append(
            "Recent deaths: "
            + "; ".join(
                f"{row.get('killed_by_agent')} killed me at={row.get('at')}"
                for row in deaths
            )
        )

    return "\n".join(lines)


def build_prompt(prompt_id, state):
    prompt = PROMPTS[prompt_id]
    context = compact_state(state)
    mention = choose_mention_target(context, prompt.get("target") or prompt["audience"])
    settings = ollama_settings()

    mention_rule = (
        "If you use the optional mention, put it at the start exactly as provided, including the trailing space. "
        "Never attach punctuation directly to a mention."
    )

    prompt_text = (
        "Write only one short English Valorant chat line.\n"
        "Maximum 90 characters. No commas. No quotes. No explanation.\n"
        "No clear insult. No threat. Never flame my team.\n"
        "Ignore HS/headshot percentage and never mention HS/headshot.\n"
        "Do not invent stats. Do not calculate ratios or percentages.\n"
        "Do not invent time windows like last 5 duels or fake counts.\n"
        "If scoreboard_stats_reliable is false, do not mention K-D KAST assists or scoreboard stats.\n"
        "For live duels, 'I killed them' means my kills and 'they killed me' means my deaths.\n"
        "Never say I killed an agent unless I killed them is greater than 0.\n"
        "Never say I am winning a duel unless I killed them is greater than they killed me.\n"
        "Write in first person as if I am sending the message myself.\n"
        "Never include my player name or any nickname variant in the output.\n"
        "Never target me never mention me and never make fun of my stats.\n"
        "Avoid animal metaphors and long poetic sentences.\n"
        f"My exact player name is {settings['player_name']}. Use it only to find my own stats.\n"
        f"Task: {prompt['instruction']}\n"
        f"Optional mention: {mention}\n"
        f"{mention_rule}\n"
        f"Match data:\n{context_lines(context, prompt_id)}"
    )

    return {
        "model": settings["model"],
        "stream": False,
        "keep_alive": settings["keep_alive"],
        "options": {
            "temperature": settings["temperature"],
            "num_predict": 96
        },
        "prompt": prompt_text
    }


def sanitize_chat_line(text, player_name=""):
    line = re.sub(r"\s+", " ", (text or "").strip())
    line = line.split("\n", 1)[0].strip('"').strip("'").strip()
    line = re.sub(r"^(message|response|answer|line|reponse|phrase)\s*:\s*", "", line, flags=re.IGNORECASE).strip()

    sentences = re.split(r"(?<=[.!?])\s+", line)
    if sentences and len(sentences[0]) >= 8:
        line = sentences[0].strip()

    line = line.replace(",", "")
    line = re.sub(r"(@[\w]+)([.!?:;])", r"\1 \2", line, flags=re.UNICODE)
    line = line.replace('"', "").replace("'", "")

    if player_name:
        line = re.sub(re.escape(player_name), "", line, flags=re.IGNORECASE).strip()
        line = re.sub(r"\bYota\w*\b", "", line, flags=re.IGNORECASE).strip()
        line = re.sub(r"\s{2,}", " ", line)

    banned_fragments = [
        "fuck", "shit", "bitch", "retard", "suicide", "kill yourself",
        "fdp", "pute", "ntm", "tg", "connard", "salope"
    ]
    lowered = line.lower()

    for fragment in banned_fragments:
        if fragment in lowered:
            return "btw your mental economy is on eco"

    french_markers = [
        " le ", " la ", " les ", " des ", " une ", " un ", " tu ", " ton ",
        " votre ", " equipe", " victoire", " defaite", " perdu", " gagne"
    ]
    padded = f" {lowered} "

    if any(marker in padded for marker in french_markers):
        return ""

    if len(line) > 90:
        line = line[:87].rstrip(" ,;:.!?") + "..."

    return line


def fallback_message(prompt_id):
    fallbacks = {
        "p1": "btw I think your mental is on eco",
        "p2": "we breathe then I turn this round back on",
        "p3": "gg I lost the map but won the duel economy",
        "p4": "my kills are quiet but my KAST pays rent",
        "p5": "I think the spike is buffering reality"
    }
    return fallbacks.get(prompt_id, "btw the spike has more philosophy than us")


def copy_to_clipboard(text):
    subprocess.run(
        ["powershell", "-NoProfile", "-Command", "Set-Clipboard -Value $input"],
        input=text,
        text=True,
        check=True
    )


def generate_message(prompt_id, state):
    if prompt_id == "disclaimer":
        copy_to_clipboard(FIXED_DISCLAIMER)
        return FIXED_DISCLAIMER, "fixed disclaimer", FIXED_DISCLAIMER

    if prompt_id not in PROMPTS:
        raise ValueError(f"Unknown prompt id: {prompt_id}")

    settings = ollama_settings()
    payload = build_prompt(prompt_id, state)
    sent_prompt = payload["prompt"]
    data = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(
        f"{settings['url']}/api/generate",
        data=data,
        headers={"Content-Type": "application/json"},
        method="POST"
    )

    try:
        with urllib.request.urlopen(req, timeout=settings["timeout"]) as response:
            body = json.loads(response.read().decode("utf-8"))
    except urllib.error.URLError as exc:
        raise RuntimeError(f"Ollama unavailable: {exc}") from exc

    raw_response = body.get("response", "")

    if not raw_response:
        retry_payload = dict(payload)
        retry_payload["prompt"] = (
            "Write only one short English Valorant chat line. "
            "No commas. No quotes. No clear insult. Never mention HS/headshot. "
            "Do not invent stats. Do not mention K-D or KAST if stats are unreliable. "
            "Write in first person as me. Never include my player name or variants. "
            f"Task: {PROMPTS[prompt_id]['instruction']} "
            f"Data: {context_lines(compact_state(state), prompt_id)}"
        )
        retry_payload["options"] = {
            "temperature": 0.7,
            "num_predict": 96
        }
        retry_req = urllib.request.Request(
            f"{settings['url']}/api/generate",
            data=json.dumps(retry_payload).encode("utf-8"),
            headers={"Content-Type": "application/json"},
            method="POST"
        )

        try:
            with urllib.request.urlopen(retry_req, timeout=settings["timeout"]) as response:
                body = json.loads(response.read().decode("utf-8"))
                raw_response = body.get("response", "")
        except urllib.error.URLError:
            pass

    message = sanitize_chat_line(raw_response, settings["player_name"]) or fallback_message(prompt_id)
    copy_to_clipboard(message)
    return message, sent_prompt, raw_response


def warm_model():
    settings = ollama_settings()
    payload = {
        "model": settings["model"],
        "prompt": "ready",
        "stream": False,
        "keep_alive": settings["keep_alive"],
        "options": {
            "num_predict": 1,
            "temperature": 0
        }
    }
    req = urllib.request.Request(
        f"{settings['url']}/api/generate",
        data=json.dumps(payload).encode("utf-8"),
        headers={"Content-Type": "application/json"},
        method="POST"
    )

    with urllib.request.urlopen(req, timeout=max(settings["timeout"], 60)) as response:
        response.read()
