import json
import os
import random
import re
import subprocess
import urllib.error
import urllib.request


DEFAULT_OLLAMA_URL = "http://192.168.1.169:11434"
DEFAULT_OLLAMA_MODEL = "llama3.2:3b"

PROMPTS = {
    "p1": {
        "hotkey": "t+u",
        "label": "Enemy tilt",
        "audience": "enemy",
        "instruction": (
            "Find the enemy who is most likely tilted, currently weak, or losing direct duels against me. "
            "Use real match facts only: score, my K-D, their K-D, live duel kills/deaths, and recent killed_by_agent. "
            "Write a safe personalized jab that makes that enemy doubt themselves without clear insults."
        )
    },
    "p2": {
        "hotkey": "t+i",
        "label": "Team reset",
        "audience": "ally",
        "instruction": (
            "Motivate my own team when the match is close or going badly. "
            "Use score and my contribution if useful. "
            "Make it weird, pseudo-philosophical, and short, like a strange coach quote from another dimension."
        )
    },
    "p3": {
        "hotkey": "t+o",
        "label": "Lost GG",
        "audience": "enemy",
        "instruction": (
            "Write a GG for the end of a lost match where my team lost but my individual stats still look strong. "
            "Use my kills/deaths or duel data if it supports the line. "
            "Sound calm, smug, and safe, not salty."
        )
    },
    "p4": {
        "hotkey": "t+p",
        "label": "Objective clapback",
        "audience": "ally",
        "instruction": (
            "Reply to a teammate who complains that I do not have enough kills. "
            "Defend me with objective impact: KAST, assists, trades, space, utility, spike or survival value. "
            "Never attack my team; make it a short calm clapback."
        )
    },
    "p5": {
        "hotkey": "t+j",
        "label": "WTF random",
        "audience": "lobby",
        "instruction": (
            "Write a completely unexpected Valorant lobby message. "
            "It can be absurd, philosophical, fake-profound, or surreal, but still connected loosely to the current match context. "
            "The goal is to make everyone pause for one second and wonder what that was."
        )
    },
    "disclaimer": {
        "hotkey": "t+k",
        "label": "Ollama disclaimer",
        "audience": "lobby",
        "instruction": "Copy the fixed disclaimer."
    }
}

FIXED_DISCLAIMER = "All my messages were generated by a local Llama 3.2 LLM"


def load_env(path=".env"):
    if not os.path.exists(path):
        return

    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue

            key, value = line.split("=", 1)
            os.environ.setdefault(key.strip(), value.strip().strip('"').strip("'"))


def ollama_settings():
    load_env()
    return {
        "url": os.environ.get("OLLAMA_URL", DEFAULT_OLLAMA_URL).rstrip("/"),
        "model": os.environ.get("OLLAMA_MODEL", DEFAULT_OLLAMA_MODEL),
        "timeout": float(os.environ.get("OLLAMA_TIMEOUT", "8")),
        "temperature": float(os.environ.get("OLLAMA_TEMPERATURE", "0.9")),
        "keep_alive": os.environ.get("OLLAMA_KEEP_ALIVE", "45m"),
        "player_name": os.environ.get("PLAYER_NAME", "Yotakipa")
    }


def public_prompts():
    return [
        {
            "id": prompt_id,
            "hotkey": prompt["hotkey"].upper(),
            "label": prompt["label"],
            "audience": prompt["audience"]
        }
        for prompt_id, prompt in PROMPTS.items()
    ]


def compact_player(row, player_name):
    name = row.get("name") or ""
    return {
        "team": row.get("team"),
        "slot": row.get("slot"),
        "name": row.get("name"),
        "is_me": name.lower() == player_name.lower(),
        "agent": row.get("agent"),
        "rank": row.get("rank"),
        "level": row.get("level"),
        "kd": row.get("kd"),
        "assists": row.get("assists"),
        "kast": row.get("kast"),
        "kpr": row.get("kpr"),
        "fkfd": row.get("fkfd")
    }


def compact_state(state):
    latest = state.get("latest") or {}
    settings = ollama_settings()
    scoreboard = [
        compact_player(row, settings["player_name"])
        for row in latest.get("scoreboard", [])
    ]

    return {
        "my_name": settings["player_name"],
        "score": latest.get("score") or state.get("score"),
        "me": next((row for row in scoreboard if row.get("is_me")), None),
        "players": scoreboard,
        "duels": latest.get("live_duels", []),
        "last_deaths": state.get("death_log", [])[-2:]
    }


def choose_mention_target(context, audience):
    rows = context.get("players", [])

    if audience == "ally":
        candidates = [row for row in rows if row.get("team") == "allies" and row.get("name")]
    else:
        candidates = [row for row in rows if row.get("team") == "enemies" and row.get("name")]

    if not candidates or random.random() >= 0.33:
        return ""

    return random.choice(candidates).get("name", "")


def context_lines(context):
    lines = [
        f"Joueur local: {context.get('my_name')}",
        f"Score: {context.get('score')}"
    ]

    me = context.get("me")
    if me:
        lines.append(
            "Mes stats: "
            f"name={me.get('name')} agent={me.get('agent')} kd={me.get('kd')} "
            f"assists={me.get('assists')} kast={me.get('kast')}"
        )

    enemies = [row for row in context.get("players", []) if row.get("team") == "enemies"][:5]
    if enemies:
        lines.append(
            "Adversaires: "
            + "; ".join(
                f"{row.get('name')} {row.get('agent')} kd={row.get('kd')} kast={row.get('kast')}"
                for row in enemies
            )
        )

    duels = context.get("duels", [])[:5]
    if duels:
        lines.append(
            "Live duels: "
            + "; ".join(
                f"{row.get('agent')} killed={row.get('kills')} killed_by={row.get('deaths')}"
                for row in duels
            )
        )

    deaths = context.get("last_deaths", [])
    if deaths:
        lines.append(
            "Dernieres morts: "
            + "; ".join(
                f"tue par {row.get('killed_by_agent')} at={row.get('at')}"
                for row in deaths
            )
        )

    return "\n".join(lines)


def build_prompt(prompt_id, state):
    prompt = PROMPTS[prompt_id]
    context = compact_state(state)
    mention = choose_mention_target(context, prompt["audience"])
    settings = ollama_settings()

    prompt_text = (
        "Donne seulement une phrase courte en francais ou franglais pour le chat Valorant.\n"
        "Maximum 90 caracteres. Pas de guillemets. Pas d'explication.\n"
        "Pas de gros mot clair. Pas de menace. Ne critique jamais mon equipe.\n"
        "Ignore totalement le pourcentage HS/headshot et ne mentionne jamais HS/headshot dans la reponse.\n"
        "Evite les metaphores animales ou trop longues.\n"
        f"Mon pseudo est {settings['player_name']}.\n"
        f"Objectif: {prompt['instruction']}\n"
        f"Mention optionnelle: {mention}\n"
        f"Donnees match:\n{context_lines(context)}"
    )

    return {
        "model": settings["model"],
        "stream": False,
        "keep_alive": settings["keep_alive"],
        "options": {
            "temperature": settings["temperature"],
            "num_predict": 96
        },
        "prompt": prompt_text
    }


def sanitize_chat_line(text):
    line = re.sub(r"\s+", " ", (text or "").strip())
    line = line.split("\n", 1)[0].strip('"').strip("'").strip()
    line = re.sub(r"^(message|reponse|phrase)\s*:\s*", "", line, flags=re.IGNORECASE).strip()

    sentences = re.split(r"(?<=[.!?])\s+", line)
    if sentences and len(sentences[0]) >= 8:
        line = sentences[0].strip()

    banned_fragments = [
        "fuck", "shit", "bitch", "retard", "suicide", "kill yourself",
        "fdp", "pute", "ntm", "tg", "connard", "salope"
    ]
    lowered = line.lower()

    for fragment in banned_fragments:
        if fragment in lowered:
            return "btw your mental economy is on eco"

    if len(line) > 90:
        line = line[:87].rstrip(" ,;:.!?") + "..."

    return line


def fallback_message(prompt_id):
    fallbacks = {
        "p1": "btw ton mental joue en eco",
        "p2": "on respire, meme le spike croit encore au projet",
        "p3": "gg, scoreboard perdu mais duel economy rentable",
        "p4": "kills ou pas, mon KAST paie le loyer",
        "p5": "le vrai lurk etait dans notre metaphysique"
    }
    return fallbacks.get(prompt_id, "btw the spike has more philosophy than us")


def copy_to_clipboard(text):
    subprocess.run(
        ["powershell", "-NoProfile", "-Command", "Set-Clipboard -Value $input"],
        input=text,
        text=True,
        check=True
    )


def generate_message(prompt_id, state):
    if prompt_id == "disclaimer":
        copy_to_clipboard(FIXED_DISCLAIMER)
        return FIXED_DISCLAIMER, "fixed disclaimer", FIXED_DISCLAIMER

    if prompt_id not in PROMPTS:
        raise ValueError(f"Unknown prompt id: {prompt_id}")

    settings = ollama_settings()
    payload = build_prompt(prompt_id, state)
    sent_prompt = payload["prompt"]
    data = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(
        f"{settings['url']}/api/generate",
        data=data,
        headers={"Content-Type": "application/json"},
        method="POST"
    )

    try:
        with urllib.request.urlopen(req, timeout=settings["timeout"]) as response:
            body = json.loads(response.read().decode("utf-8"))
    except urllib.error.URLError as exc:
        raise RuntimeError(f"Ollama unavailable: {exc}") from exc

    raw_response = body.get("response", "")

    if not raw_response:
        retry_payload = dict(payload)
        retry_payload["prompt"] = (
            "Donne seulement une phrase courte en francais pour Valorant. "
            "Pas de gros mot. Ne mentionne jamais HS/headshot. "
            f"Objectif: {PROMPTS[prompt_id]['instruction']} "
            f"Donnees: {context_lines(compact_state(state))}"
        )
        retry_payload["options"] = {
            "temperature": 0.7,
            "num_predict": 96
        }
        retry_req = urllib.request.Request(
            f"{settings['url']}/api/generate",
            data=json.dumps(retry_payload).encode("utf-8"),
            headers={"Content-Type": "application/json"},
            method="POST"
        )

        try:
            with urllib.request.urlopen(retry_req, timeout=settings["timeout"]) as response:
                body = json.loads(response.read().decode("utf-8"))
                raw_response = body.get("response", "")
        except urllib.error.URLError:
            pass

    message = sanitize_chat_line(raw_response) or fallback_message(prompt_id)
    copy_to_clipboard(message)
    return message, sent_prompt, raw_response


def warm_model():
    settings = ollama_settings()
    payload = {
        "model": settings["model"],
        "prompt": "ready",
        "stream": False,
        "keep_alive": settings["keep_alive"],
        "options": {
            "num_predict": 1,
            "temperature": 0
        }
    }
    req = urllib.request.Request(
        f"{settings['url']}/api/generate",
        data=json.dumps(payload).encode("utf-8"),
        headers={"Content-Type": "application/json"},
        method="POST"
    )

    with urllib.request.urlopen(req, timeout=max(settings["timeout"], 60)) as response:
        response.read()
